// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq3YTt1VQ7F4P11bxrqHKgt0KK8uoS7Sw',
    appId: '1:257020829815:web:11b4ace5d9a86f99bbe672',
    messagingSenderId: '257020829815',
    projectId: 'quick-pick-app-35c4e',
    authDomain: 'quick-pick-app-35c4e.firebaseapp.com',
    storageBucket: 'quick-pick-app-35c4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAly1tx4uuOCbiAJh_xtV_wqD3GlSs54',
    appId: '1:257020829815:android:420cb8f37b1cec52bbe672',
    messagingSenderId: '257020829815',
    projectId: 'quick-pick-app-35c4e',
    storageBucket: 'quick-pick-app-35c4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4dmFmR6OZBBY2eEeyZZbg7866rJK-B1c',
    appId: '1:257020829815:ios:e37618949b7e3772bbe672',
    messagingSenderId: '257020829815',
    projectId: 'quick-pick-app-35c4e',
    storageBucket: 'quick-pick-app-35c4e.appspot.com',
    iosClientId: '257020829815-j8gvnr1ksm90edsl3qpb4oumnfcr6tpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickPickApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4dmFmR6OZBBY2eEeyZZbg7866rJK-B1c',
    appId: '1:257020829815:ios:e37618949b7e3772bbe672',
    messagingSenderId: '257020829815',
    projectId: 'quick-pick-app-35c4e',
    storageBucket: 'quick-pick-app-35c4e.appspot.com',
    iosClientId: '257020829815-j8gvnr1ksm90edsl3qpb4oumnfcr6tpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickPickApp',
  );
}
